FROM cypress/included:15.3.0
WORKDIR /e2e

# Copy frontend code (for tests)
COPY package*.json ./
RUN npm ci
COPY . .

# Environment variable for backend URL
ENV CYPRESS_baseUrl=http://backend:8080

# Verify Cypress binary
RUN npx cypress verify
