version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flask_app
    ports:
      - "8080:8080" # Flask runs on 8080
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    command: python app.py

  frontend:
    build: ./frontend
    container_name: nextjs_app
    ports:
      - "3000:3000" # Next.js dev server
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    volumes:
      - ./frontend:/app
    command: npm run build && npm start
