version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flask_app
    ports:
      - "8080:8080" # Flask runs on 8080
    environment:
      - FLASK_ENV=production
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --port=8080

  frontend:
    build: ./frontend
    container_name: nextjs_app
    ports:
      - "3000:3000" # Next.js dev server
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
    command: npm run dev
