version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
