name: CI/CD with Render

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose curl jq

      # Build and run containers
      - name: Build and start containers
        run: docker-compose -f docker-compose.yml up --build -d

      # Run backend tests
      - name: Run backend tests
        run: docker exec flask_app pytest

      # Run frontend tests
      - name: Run frontend E2E tests
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/frontend:/e2e \
            cypress/included:12.17.1 \
            cypress run --headless --browser chrome --config baseUrl=http://localhost:3000
      
      # Optionally run integration / E2E tests
      # - name: Run frontend integration tests
      #   run: docker exec -e CI=true nextjs_app npm run test:integration

      # - name: Run frontend E2E tests
      #   run: docker exec -e CI=true nextjs_app npm run cypress:run

      # Tear down
      - name: Tear down test containers
        run: docker-compose down --volumes --remove-orphans

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to Render
        run: |
          DEPLOY_BACKEND=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/${{ secrets.RENDER_BACKEND_SERVICE_ID }}/deploys)
          echo "Backend deploy started: $DEPLOY_BACKEND"

      - name: Deploy frontend to Render
        run: |
          DEPLOY_FRONTEND=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/${{ secrets.RENDER_FRONTEND_SERVICE_ID }}/deploys)
          echo "Frontend deploy started: $DEPLOY_FRONTEND"
