
name: Docker Compose

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run services
      run: |
        docker-compose -f docker-compose.yml up -d --build

    - name: Wait for services to be ready
      run: sleep 10

    - name: Run backend tests
      run: docker exec backend pytest

    - name: Run frontend tests
      run: docker exec frontend npm run test

    - name: Tear down
      run: docker-compose down

