name: Docker Compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Install docker-compose
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose curl

      # 4. Build and start containers
      - name: Build and start services
        run: docker-compose -f docker-compose.yml up --build -d

      # 5. Wait for Flask app to be ready
      - name: Wait for Flask app
        run: |
          echo "Waiting for Flask app..."
          for i in {1..30}; do
            if curl --silent --fail http://localhost:5000/health; then
              echo "Flask app is ready!"
              break
            else
              echo "Waiting..."
              sleep 2
            fi
          done

      # 6. Run backend tests
      - name: Run backend tests
        run: docker exec flask_app pytest

      # 7. Run frontend tests
     
      - name: Set version tag
        run: echo "VERSION_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Save backend image
        run: docker save healthcare_sytem_backend:v1.0.0 -o backend.tar

      - name: Save frontend image
        run: docker save healthcare_sytem_frontend:v1.0.0 -o frontend.tar

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-image
          path: backend.tar

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-image
          path: frontend.tar
      
      - name: Tear down
        run: docker-compose down --volumes --remove-orphans
