name: NextJs CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          echo "Running Installing Dependencies"
          npm install
          working-directory: ./frontend
      - name: Run Lint
        run: |
          echo "Running Lint"
          npm run lint
          working-directory: ./frontend
        env:
          CI: true

  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Check 0"
          sleep 5s;
          echo "Running Security Check 1"
          sleep 5s;
          echo "Running Security Check 2"
          sleep 5s;
          echo "Running Security Check 3"
          sleep 5s;
